### DISCUSSION TITLE
RFC: nebula-importer

### DISCUSSION THREAD

**Discussion by geofmureithi** [eigerco/nebula#11] [Ideas]
# Summary
A simplified contract management for soroban. This is an improvement to the current cross-contract example.

## Basic Example
A basic example showing how to do basic dependency management of contracts instead of having to compile or manage .wasm files.

```toml
[build-dependencies]
nebula-importer = { git = "https://github.com/eigerco/nebula" }
```

### Create a `build.rs`

```rs
fn main() {
    nebula_importer::sync_all_contracts();
}
```

### Create the dependency metadata in `Cargo.toml` with imported contracts

```toml
[package.metadata.nebula.imports]
token = "ghcr.io/eigerco/nebula/contracts/token"
voting = "ghcr.io/eigerco/nebula/contracts/voting:latest"
```

### Use the contracts in your lib.rs

```rust
mod contracts {
    include!(concat!(env!("OUT_DIR"), "/nebula_importer.rs"));
}

fn main() {
    let client = contracts::voting::Client::new();
    // .....
}
```

# Motivation
Currently importing a contract works like this:
```rust
mod contract_a {
    soroban_sdk::contractimport!(
        file = "../contract_a/target/wasm32-unknown-unknown/release/soroban_cross_contract_a_contract.wasm"
    );
}
```
This has several downsides:
- You need the contract to be compiled/exist locally.
- There is no specific standard to fetch and use contracts.

# Detailed description
Under the hood, we are going to hook a file to the build process. 
It will try to find the contract in cache else download it.
It will rebuild every time it changes.

It still uses `soroban_sdk::contractimport` under the hood.
We are using OCI and any valid registry eg Github packages can be used
